### ISSUE TITLE
Gather basic requirements

### ISSUE THREAD

**Issue by jcarolev** [markcablayan/cmpe202-project#10]
"Map out" how the game will be played - define actions each player can take, the rules of the game, what the win conditions are, etc.

**Comment by tuanungquoc** [comment]
- Each player will have 2 same color items that match with their shirt color in their hand except one player with one item. Item could be fruit, candy, or something is differentiated to each other by color.
- Since the simplicity, we should start with the round shape. That means a player can only pass to their neighbor when his neighbor has only 1 item in his hand. 
- The games is only started when we have enough people joining the games. Let's say we define a game with 3 ppl playing. Each person will join the board until we have enough ppl. Then we lock the game and start the game.
- Starting the games, we will randomly distribute items for each player 
- Since this is not "a winning" games, it is a simulation of the activity. The stoping game point will be when all players have 2 items in their hand and their color should be matched with the player's shirt color. 
- Later on, we can extend the activity by having them choose the shape that they want to play for example: a straight line. And depending on shape, the rule will be different.  But right now, we should make it simple first with a circular shape.
